### PR TITLE
 Make it possible to omit specifying the inventory file when executing the ansible-playbook command

### PR DESCRIPTION
**Pull request by wate**
Added ansible.cfg file so that it can be omitted by specifying `-i hosts` at runtime

### CODE REVIEW

**Comment by higebu** [comment]
Thank you for your pull request
But cloud you please use English? Because VyOS projects communicate in English.

**Comment by wate** [comment]
@higebu Thank you for pointing out, I modified the content of pull request to English

**Comment by higebu** [comment]
@wate Please modify the commit message too. Thanks.

**Comment by wate** [comment]
@higebu Fixed commit message

**Comment by higebu** [comment]
@wate I think `Add ansible.cfg...` is good as you write on the description. For example: `Add ansible.cfg to specify the default inventory path`

**Comment by wate** [comment]
@higebu Thank you for your advice, I think that person is certainly easy to understand.

**Pull request merged**
