### PR TITLE
T4838: Add Vagrant SSH key for vagrant-libvirt build

### PR DESCRIPTION
**Pull request by ssasso**
Following https://phabricator.vyos.net/T4838

### CODE REVIEW

**Comment by sever-sever** [comment]
Commit headlines should contain a valid Task id

**Comment by ssasso** [comment]
> Commit headlines should contain a valid Task id

thanks, re-committed and force pushed.

**Review by higebu — APPROVED** [review]
I tested the PR on local machine, and the box works fine.

**Review by zdc — CHANGES_REQUESTED** [review]
Hello, @ssasso! Thanks for the PR!

I would like to ask you to change it in a different way. Instead of hardcoding a key, please just add a new environment variable (for example `default_ssh_key` or similar), so the key can be customized and used for all the target platforms.

Then you can use Ansible environment if you want to hardcode it in your personal build system.

**Comment by ssasso** [comment]
I will use a more generic name for it, but a value for the key is still required on the vagrant playbook, with the default vagrant insecure key (to address the bug https://phabricator.vyos.net/T4838). See also  https://github.com/hashicorp/vagrant/tree/main/keys

**Comment by ssasso** [comment]
any feedback on this @zdc ?

**Comment by sever-sever** [comment]
@zdc could you take a look?

**Comment by dmbaturin** [comment]
The change request about the hardcoded key was not addressed and the  PR has been stale for a while, closing.

**Pull request closed without merging**
